// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/trsv-dev/simple-windows-services-monitor/internal/service_control (interfaces: Fingerprinter)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockFingerprinter is a mock of Fingerprinter interface.
type MockFingerprinter struct {
	ctrl     *gomock.Controller
	recorder *MockFingerprinterMockRecorder
}

// MockFingerprinterMockRecorder is the mock recorder for MockFingerprinter.
type MockFingerprinterMockRecorder struct {
	mock *MockFingerprinter
}

// NewMockFingerprinter creates a new mock instance.
func NewMockFingerprinter(ctrl *gomock.Controller) *MockFingerprinter {
	mock := &MockFingerprinter{ctrl: ctrl}
	mock.recorder = &MockFingerprinterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFingerprinter) EXPECT() *MockFingerprinterMockRecorder {
	return m.recorder
}

// GetFingerprint mocks base method.
func (m *MockFingerprinter) GetFingerprint(arg0 context.Context, arg1, arg2, arg3 string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFingerprint", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFingerprint indicates an expected call of GetFingerprint.
func (mr *MockFingerprinterMockRecorder) GetFingerprint(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFingerprint", reflect.TypeOf((*MockFingerprinter)(nil).GetFingerprint), arg0, arg1, arg2, arg3)
}
