// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/trsv-dev/simple-windows-services-monitor/internal/auth (interfaces: TokenBuilder)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	auth "github.com/trsv-dev/simple-windows-services-monitor/internal/auth"
	models "github.com/trsv-dev/simple-windows-services-monitor/internal/models"
)

// MockTokenBuilder is a mock of TokenBuilder interface.
type MockTokenBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockTokenBuilderMockRecorder
}

// MockTokenBuilderMockRecorder is the mock recorder for MockTokenBuilder.
type MockTokenBuilderMockRecorder struct {
	mock *MockTokenBuilder
}

// NewMockTokenBuilder creates a new mock instance.
func NewMockTokenBuilder(ctrl *gomock.Controller) *MockTokenBuilder {
	mock := &MockTokenBuilder{ctrl: ctrl}
	mock.recorder = &MockTokenBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenBuilder) EXPECT() *MockTokenBuilderMockRecorder {
	return m.recorder
}

// BuildJWTToken mocks base method.
func (m *MockTokenBuilder) BuildJWTToken(arg0 *models.User, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildJWTToken", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildJWTToken indicates an expected call of BuildJWTToken.
func (mr *MockTokenBuilderMockRecorder) BuildJWTToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildJWTToken", reflect.TypeOf((*MockTokenBuilder)(nil).BuildJWTToken), arg0, arg1)
}

// GetClaims mocks base method.
func (m *MockTokenBuilder) GetClaims(arg0, arg1 string) (*auth.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClaims", arg0, arg1)
	ret0, _ := ret[0].(*auth.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClaims indicates an expected call of GetClaims.
func (mr *MockTokenBuilderMockRecorder) GetClaims(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClaims", reflect.TypeOf((*MockTokenBuilder)(nil).GetClaims), arg0, arg1)
}
