// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/trsv-dev/simple-windows-services-monitor/internal/health_storage (interfaces: StatusCacheStorage)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/trsv-dev/simple-windows-services-monitor/internal/models"
)

// MockStatusCacheStorage is a mock of StatusCacheStorage interface.
type MockStatusCacheStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStatusCacheStorageMockRecorder
}

// MockStatusCacheStorageMockRecorder is the mock recorder for MockStatusCacheStorage.
type MockStatusCacheStorageMockRecorder struct {
	mock *MockStatusCacheStorage
}

// NewMockStatusCacheStorage creates a new mock instance.
func NewMockStatusCacheStorage(ctrl *gomock.Controller) *MockStatusCacheStorage {
	mock := &MockStatusCacheStorage{ctrl: ctrl}
	mock.recorder = &MockStatusCacheStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusCacheStorage) EXPECT() *MockStatusCacheStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockStatusCacheStorage) Delete(arg0 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", arg0)
}

// Delete indicates an expected call of Delete.
func (mr *MockStatusCacheStorageMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStatusCacheStorage)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockStatusCacheStorage) Get(arg0 int64) (models.ServerStatus, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(models.ServerStatus)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStatusCacheStorageMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStatusCacheStorage)(nil).Get), arg0)
}

// GetAllServerStatusesByUser mocks base method.
func (m *MockStatusCacheStorage) GetAllServerStatusesByUser(arg0 int64) []models.ServerStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllServerStatusesByUser", arg0)
	ret0, _ := ret[0].([]models.ServerStatus)
	return ret0
}

// GetAllServerStatusesByUser indicates an expected call of GetAllServerStatusesByUser.
func (mr *MockStatusCacheStorageMockRecorder) GetAllServerStatusesByUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllServerStatusesByUser", reflect.TypeOf((*MockStatusCacheStorage)(nil).GetAllServerStatusesByUser), arg0)
}

// Set mocks base method.
func (m *MockStatusCacheStorage) Set(arg0 models.ServerStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", arg0)
}

// Set indicates an expected call of Set.
func (mr *MockStatusCacheStorageMockRecorder) Set(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockStatusCacheStorage)(nil).Set), arg0)
}
