// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/trsv-dev/simple-windows-services-monitor/internal/storage (interfaces: WorkerStorage)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/trsv-dev/simple-windows-services-monitor/internal/models"
)

// MockWorkerStorage is a mock of WorkerStorage interface.
type MockWorkerStorage struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerStorageMockRecorder
}

// MockWorkerStorageMockRecorder is the mock recorder for MockWorkerStorage.
type MockWorkerStorageMockRecorder struct {
	mock *MockWorkerStorage
}

// NewMockWorkerStorage creates a new mock instance.
func NewMockWorkerStorage(ctrl *gomock.Controller) *MockWorkerStorage {
	mock := &MockWorkerStorage{ctrl: ctrl}
	mock.recorder = &MockWorkerStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerStorage) EXPECT() *MockWorkerStorageMockRecorder {
	return m.recorder
}

// ListServersAddresses mocks base method.
func (m *MockWorkerStorage) ListServersAddresses(arg0 context.Context) ([]*models.ServerStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServersAddresses", arg0)
	ret0, _ := ret[0].([]*models.ServerStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServersAddresses indicates an expected call of ListServersAddresses.
func (mr *MockWorkerStorageMockRecorder) ListServersAddresses(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServersAddresses", reflect.TypeOf((*MockWorkerStorage)(nil).ListServersAddresses), arg0)
}
