// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/trsv-dev/simple-windows-services-monitor/internal/worker (interfaces: StatusesChecker)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/trsv-dev/simple-windows-services-monitor/internal/models"
)

// MockStatusesChecker is a mock of StatusesChecker interface.
type MockStatusesChecker struct {
	ctrl     *gomock.Controller
	recorder *MockStatusesCheckerMockRecorder
}

// MockStatusesCheckerMockRecorder is the mock recorder for MockStatusesChecker.
type MockStatusesCheckerMockRecorder struct {
	mock *MockStatusesChecker
}

// NewMockStatusesChecker creates a new mock instance.
func NewMockStatusesChecker(ctrl *gomock.Controller) *MockStatusesChecker {
	mock := &MockStatusesChecker{ctrl: ctrl}
	mock.recorder = &MockStatusesCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusesChecker) EXPECT() *MockStatusesCheckerMockRecorder {
	return m.recorder
}

// CheckServiceStatuses mocks base method.
func (m *MockStatusesChecker) CheckServiceStatuses(arg0 context.Context, arg1 *models.Server, arg2 []*models.Service) ([]*models.Service, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckServiceStatuses", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.Service)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// CheckServiceStatuses indicates an expected call of CheckServiceStatuses.
func (mr *MockStatusesCheckerMockRecorder) CheckServiceStatuses(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckServiceStatuses", reflect.TypeOf((*MockStatusesChecker)(nil).CheckServiceStatuses), arg0, arg1, arg2)
}
